[phases.setup]
nixPkgs = ["ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "cp -r alembic /app/",
    "cp alembic.ini /app/",
    "echo 'Build completed'"
]

[start]
cmd = "python -m src.main"
