[phases.setup]
nixPkgs = ["ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "ls -la",
    "echo 'Build completed'"
]

[start]
cmd = "python -m src.main"
