[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m src.main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { ENVIRONMENT = "production", DEBUG = "False" }
